//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SisAD.sislogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutenticaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractBaseResponse))]
    public partial class Autentica : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Autentica() {
            this.Url = global::SisAD.Properties.Settings.Default.SisAD_sislogin_Autentica;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarUsuarioCompletedEventHandler CadastrarUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarSenhaCompletedEventHandler AlterarSenhaCompleted;
        
        /// <remarks/>
        public event AutenticarUsuarioCompletedEventHandler AutenticarUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuarioCompletedEventHandler ListarUsuarioCompleted;
        
        /// <remarks/>
        public event CancelarUsuarioCompletedEventHandler CancelarUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result CadastrarUsuario(string txt_nome, string txt_senha, string txt_email) {
            object[] results = this.Invoke("CadastrarUsuario", new object[] {
                        txt_nome,
                        txt_senha,
                        txt_email});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(string txt_nome, string txt_senha, string txt_email) {
            this.CadastrarUsuarioAsync(txt_nome, txt_senha, txt_email, null);
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(string txt_nome, string txt_senha, string txt_email, object userState) {
            if ((this.CadastrarUsuarioOperationCompleted == null)) {
                this.CadastrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("CadastrarUsuario", new object[] {
                        txt_nome,
                        txt_senha,
                        txt_email}, this.CadastrarUsuarioOperationCompleted, userState);
        }
        
        private void OnCadastrarUsuarioOperationCompleted(object arg) {
            if ((this.CadastrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarUsuarioCompleted(this, new CadastrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result AlterarUsuario(int id, string txt_nome, string txt_email) {
            object[] results = this.Invoke("AlterarUsuario", new object[] {
                        id,
                        txt_nome,
                        txt_email});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(int id, string txt_nome, string txt_email) {
            this.AlterarUsuarioAsync(id, txt_nome, txt_email, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(int id, string txt_nome, string txt_email, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        id,
                        txt_nome,
                        txt_email}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new AlterarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarSenha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result AlterarSenha(int id, string txt_senha_atual, string txt_nova_senha) {
            object[] results = this.Invoke("AlterarSenha", new object[] {
                        id,
                        txt_senha_atual,
                        txt_nova_senha});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarSenhaAsync(int id, string txt_senha_atual, string txt_nova_senha) {
            this.AlterarSenhaAsync(id, txt_senha_atual, txt_nova_senha, null);
        }
        
        /// <remarks/>
        public void AlterarSenhaAsync(int id, string txt_senha_atual, string txt_nova_senha, object userState) {
            if ((this.AlterarSenhaOperationCompleted == null)) {
                this.AlterarSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarSenhaOperationCompleted);
            }
            this.InvokeAsync("AlterarSenha", new object[] {
                        id,
                        txt_senha_atual,
                        txt_nova_senha}, this.AlterarSenhaOperationCompleted, userState);
        }
        
        private void OnAlterarSenhaOperationCompleted(object arg) {
            if ((this.AlterarSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarSenhaCompleted(this, new AlterarSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result AutenticarUsuario(string txt_email, string txt_senha) {
            object[] results = this.Invoke("AutenticarUsuario", new object[] {
                        txt_email,
                        txt_senha});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarUsuarioAsync(string txt_email, string txt_senha) {
            this.AutenticarUsuarioAsync(txt_email, txt_senha, null);
        }
        
        /// <remarks/>
        public void AutenticarUsuarioAsync(string txt_email, string txt_senha, object userState) {
            if ((this.AutenticarUsuarioOperationCompleted == null)) {
                this.AutenticarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AutenticarUsuario", new object[] {
                        txt_email,
                        txt_senha}, this.AutenticarUsuarioOperationCompleted, userState);
        }
        
        private void OnAutenticarUsuarioOperationCompleted(object arg) {
            if ((this.AutenticarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarUsuarioCompleted(this, new AutenticarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result ListarUsuario(string id, string txt_nome, string txt_email) {
            object[] results = this.Invoke("ListarUsuario", new object[] {
                        id,
                        txt_nome,
                        txt_email});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(string id, string txt_nome, string txt_email) {
            this.ListarUsuarioAsync(id, txt_nome, txt_email, null);
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(string id, string txt_nome, string txt_email, object userState) {
            if ((this.ListarUsuarioOperationCompleted == null)) {
                this.ListarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarUsuario", new object[] {
                        id,
                        txt_nome,
                        txt_email}, this.ListarUsuarioOperationCompleted, userState);
        }
        
        private void OnListarUsuarioOperationCompleted(object arg) {
            if ((this.ListarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuarioCompleted(this, new ListarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Result CancelarUsuario(int id) {
            object[] results = this.Invoke("CancelarUsuario", new object[] {
                        id});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarUsuarioAsync(int id) {
            this.CancelarUsuarioAsync(id, null);
        }
        
        /// <remarks/>
        public void CancelarUsuarioAsync(int id, object userState) {
            if ((this.CancelarUsuarioOperationCompleted == null)) {
                this.CancelarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarUsuarioOperationCompleted);
            }
            this.InvokeAsync("CancelarUsuario", new object[] {
                        id}, this.CancelarUsuarioOperationCompleted, userState);
        }
        
        private void OnCancelarUsuarioOperationCompleted(object arg) {
            if ((this.CancelarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarUsuarioCompleted(this, new CancelarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result : AbstractBaseResponse {
        
        private Usuario[] usuariosField;
        
        private string statusField;
        
        /// <remarks/>
        public Usuario[] Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private string txt_nomeField;
        
        private string txt_senhaField;
        
        private string txt_nova_senhaField;
        
        private string txt_emailField;
        
        private bool cod_ativoField;
        
        private int idField;
        
        /// <remarks/>
        public string txt_nome {
            get {
                return this.txt_nomeField;
            }
            set {
                this.txt_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string txt_senha {
            get {
                return this.txt_senhaField;
            }
            set {
                this.txt_senhaField = value;
            }
        }
        
        /// <remarks/>
        public string txt_nova_senha {
            get {
                return this.txt_nova_senhaField;
            }
            set {
                this.txt_nova_senhaField = value;
            }
        }
        
        /// <remarks/>
        public string txt_email {
            get {
                return this.txt_emailField;
            }
            set {
                this.txt_emailField = value;
            }
        }
        
        /// <remarks/>
        public bool cod_ativo {
            get {
                return this.cod_ativoField;
            }
            set {
                this.cod_ativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionTO {
        
        private string messageField;
        
        private string detailField;
        
        private string keyField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionResponse {
        
        private string messageField;
        
        private ExceptionTO[] exceptionsField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionTO[] exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AbstractBaseResponse {
        
        private ExceptionResponse exceptionField;
        
        /// <remarks/>
        public ExceptionResponse exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CadastrarUsuarioCompletedEventHandler(object sender, CadastrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, AlterarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AlterarSenhaCompletedEventHandler(object sender, AlterarSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void AutenticarUsuarioCompletedEventHandler(object sender, AutenticarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void ListarUsuarioCompletedEventHandler(object sender, ListarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CancelarUsuarioCompletedEventHandler(object sender, CancelarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591